using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace Sandogh_TG
{
    public partial class FrmDaftarRozname : DevExpress.XtraEditors.XtraForm
    {
        FrmMain Fm;
        public FrmDaftarRozname(FrmMain fm)
        {
            InitializeComponent();
            Fm = fm;
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Sandogh_TG.MyContext dbContext = new Sandogh_TG.MyContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.AsnadeHesabdariRows.OrderBy(f=>f.ShomareSanad).Load();
            // This line of code is generated by Data Source Configuration Wizard
            asnadeHesabdariRowsBindingSource.DataSource = dbContext.AsnadeHesabdariRows.Local.ToBindingList();
        }

        private void gridView1_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            HelpClass1.SetNumberRowsColumnUnboundGirdView(sender, e);
        }
    }
}