using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraSplashScreen;

namespace Sandogh_PG.Forms
{
    public partial class FrmNobatVam : DevExpress.XtraEditors.XtraForm
    {
        FrmMain Fm;
        public FrmNobatVam(FrmMain fm)
        {
            InitializeComponent();
            Fm = fm;
            //        // This line of code is generated by Data Source Configuration Wizard
            //        // Instantiate a new DBContext
            //        Sandogh_PG.MyContext dbContext = new Sandogh_PG.MyContext();
            //        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //        dbContext.AazaSandoghs.LoadAsync().ContinueWith(loadTask =>
            //        {
            //// Bind data to control when loading complete
            //aazaSandoghsBindingSource.DataSource = dbContext.AazaSandoghs.Local.ToBindingList();
            //        }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //        Sandogh_PG.MyContext dbContext = new Sandogh_PG.MyContext();
            //        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //        dbContext.AazaSandoghs.LoadAsync().ContinueWith(loadTask =>
            //        {
            //// Bind data to control when loading complete
            //aazaSandoghsBindingSource1.DataSource = dbContext.AazaSandoghs.Local.ToBindingList();
            //        }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //        Sandogh_PG.MyContext dbContext = new Sandogh_PG.MyContext();
            //        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //        dbContext.AazaSandoghs.LoadAsync().ContinueWith(loadTask =>
            //        {
            //// Bind data to control when loading complete
            //aazaSandoghsBindingSource2.DataSource = dbContext.AazaSandoghs.Local.ToBindingList();
            //        }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //        Sandogh_PG.MyContext dbContext = new Sandogh_PG.MyContext();
            //        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //        dbContext.AazaSandoghs.LoadAsync().ContinueWith(loadTask =>
            //        {
            //// Bind data to control when loading complete
            //aazaSandoghsBindingSource.DataSource = dbContext.AazaSandoghs.Local.ToBindingList();
            //        }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        public int _IDSandogh = 0;
        int _IndexNoeVam0 = -1;
        int _IndexNoeVam1 = -1;
        int _IndexNoeVam2 = -1;
        int _IndexNoeVam3 = -1;
        List<AazaSandogh> List1=new List<AazaSandogh>();
        List<AazaSandogh> List2=new List<AazaSandogh>();
        List<AazaSandogh> List3= new List<AazaSandogh>();
        private void btnDisplyList_Click(object sender, EventArgs e)
        {
            using (var db = new MyContext())
            {
                try
                {
                    SplashScreenManager.ShowForm(this, typeof(WaitForm1), true, true, false);

                    _IndexNoeVam0 = checkEdit1.Checked ? 0 : -1;
                    _IndexNoeVam1 = checkEdit2.Checked ? 1 : -1;
                    _IndexNoeVam2 = checkEdit3.Checked ? 2 : -1;
                    _IndexNoeVam3 = checkEdit4.Checked ? 3 : -1;
                    var q1 = db.AazaSandoghs.Where(s => s.IsActive == true).AsParallel();
                    var q2 = db.VamPardakhtis.AsParallel();
                    var q4 = db.AsnadeHesabdariRows.Where(f => f.HesabMoinCode == 7001 && f.HesabTafCode >= 7000001 && f.HesabTafCode <= 7999999).AsParallel();
                    var ho = db.HaghOzviats.AsParallel();

                    List<AazaSandogh> List = new List<AazaSandogh>();
                    var q3 = q2.Where(s => s.IsTasviye == false && (s.IndexNoeVam == _IndexNoeVam0 || s.IndexNoeVam == _IndexNoeVam1 || s.IndexNoeVam == _IndexNoeVam2 || s.IndexNoeVam == _IndexNoeVam3)).AsParallel();

                    if (xtraTabControl1.SelectedTabPageIndex == 0)
                    {
                        foreach (var item in q1)
                        {


                            item.SharhHesab = q3.FirstOrDefault(s => s.AazaId == item.AllTafId) != null ? q3.FirstOrDefault(s => s.AazaId == item.AllTafId).NoeVam : "";
                            //item.TarikhOzviat = item.TarikhOzviat;
                            item.TarikhTasviyeVam = q3.FirstOrDefault(s => s.AazaId == item.AllTafId) != null ? q3.FirstOrDefault(s => s.AazaId == item.AllTafId).TarikhPardakht : Convert.ToDateTime("0001/01/01");

                            var q5 = q4.Where(f => f.HesabTafCode == item.Code);
                            decimal _SumBed = q5.Sum(f => f.Bed ?? 0);
                            decimal _SumBes = q5.Sum(f => f.Bes ?? 0);
                            decimal Mablagh = _SumBed - _SumBes;

                            item.DaramadeMahiane = Mablagh;
                            List.Add(item);

                        }

                        aazaSandoghsBindingSource0.DataSource = List.OrderBy(s => s.TarikhOzviat);
                    }
                    else if (xtraTabControl1.SelectedTabPageIndex == 1)
                    {
                        foreach (var item in q1)
                        {
                            //item.SharhHesab = q3.FirstOrDefault(s => s.AazaId == item.AllTafId) == null ? "ندارد":"دارد";
                            item.SharhHesab = q3.FirstOrDefault(s => s.AazaId == item.AllTafId) != null ? q3.FirstOrDefault(s => s.AazaId == item.AllTafId).NoeVam : "";
                            //item.TarikhTasviyeVam = q3.FirstOrDefault(s => s.AazaId == item.AllTafId) != null ? q3.FirstOrDefault(s => s.AazaId == item.AllTafId).TarikhPardakht : Convert.ToDateTime("0001/01/01");
                            item.TarikhTasviyeVam = q3.FirstOrDefault(s => s.AazaId == item.AllTafId) != null ? q3.FirstOrDefault(s => s.AazaId == item.AllTafId).TarikhPardakht : Convert.ToDateTime("0001/01/01");

                            var q5 = q4.Where(f => f.HesabTafCode == item.Code);
                            decimal _SumBed = q5.Sum(f => f.Bed ?? 0);
                            decimal _SumBes = q5.Sum(f => f.Bes ?? 0);
                            decimal Mablagh = _SumBed - _SumBes;

                            item.DaramadeMahiane = Mablagh;
                            List.Add(item);

                        }
                        aazaSandoghsBindingSource1.DataSource = List.OrderBy(s => s.NobatbandiVam);
                    }
                    else if (xtraTabControl1.SelectedTabPageIndex == 2)
                    {
                        //foreach (var item in q1)
                        //{
                        //    if (q2.FirstOrDefault(s => s.AazaId == item.AllTafId) == null)
                        //    {
                        //        int yyyy1 = Convert.ToInt32(item.TarikhTasviyeVam.ToString().Substring(0, 4));
                        //        int MM1 = Convert.ToInt32(item.TarikhTasviyeVam.ToString().Substring(5, 2));
                        //        int dd1 = Convert.ToInt32(item.TarikhTasviyeVam.ToString().Substring(8, 2));
                        //        Mydate d1 = new Mydate(yyyy1, MM1, dd1);
                        //        int _index = cmbNoeVam.SelectedIndex;
                        //        int ModatEntezar = db.Tanzimats.FirstOrDefault(s=>s.SandoghId== _IDSandogh).AnvaeVams.FirstOrDefault(s=>s.NoeVamIndex== _index).MinModatEntezar;
                        //        item.TarikhTasviyeVam = Convert.ToDateTime(d1.AddMont(ModatEntezar));
                        //        List.Add(item);
                        //    }
                        //    else if (q2.FirstOrDefault(s => s.AazaId == item.AllTafId && s.IsTasviye == false) != null)
                        //    {
                        //        continue;
                        //    }
                        //    else if (q2.FirstOrDefault(s => s.AazaId == item.AllTafId && s.IsTasviye == true) != null)
                        //    {
                        //        var q5 = db.RizeAghsatVams.Where(s => s.AazaId == item.AllTafId).Max(s => s.TarikhDaryaft);
                        //        item.TarikhTasviyeVam = Convert.ToDateTime(q5);
                        //        List.Add(item);
                        //    }
                        //}

                        //var q3 = q2.Where(s =>s.IsTasviye == false && (s.IndexNoeVam == 0 || s.IndexNoeVam == 1)).AsParallel();
                        //foreach (var item in q1)
                        //{
                        //    if (q3.FirstOrDefault(s => s.AazaId == item.AllTafId) == null)
                        //    {
                        //        //q1.Remove(item);
                        //        List.Add(item);
                        //    }
                        //}

                        string Label = string.Empty;
                        Label += checkEdit1.Checked ? checkEdit1.Text + ", " : "";
                        Label += checkEdit2.Checked ? checkEdit2.Text + ", " : "";
                        Label += checkEdit3.Checked ? checkEdit3.Text + ", " : "";
                        Label += checkEdit4.Checked ? checkEdit4.Text + ", " : "";
                        labelControl21.Text = "در این گزارش اعضایی که " + Label + " ندارند نمایش داده میشود";

                        foreach (var item in q1)
                        {
                            if (q3.FirstOrDefault(s => s.AazaId == item.AllTafId) == null)
                            {
                                //q1.Remove(item);
                                //int _CodeMoin = 7001;
                                //int _CodeTafzil = item.Code;
                                //tem.TarikhTasviyeVam = item.TarikhTasviyeVam;

                                var q5 = q4.Where(f => f.HesabTafCode == item.Code);
                                decimal _SumBed = q5.Sum(f => f.Bed ?? 0);
                                decimal _SumBes = q5.Sum(f => f.Bes ?? 0);
                                decimal Mablagh = _SumBed - _SumBes;

                                item.DaramadeMahiane = Mablagh;
                                List.Add(item);
                            }
                        }

                        aazaSandoghsBindingSource2.DataSource = List.OrderBy(s => s.TarikhTasviyeVam);
                    }
                    else if (xtraTabControl1.SelectedTabPageIndex == 3)
                    {
                        var q30 = q2.Where(s => s.IndexNoeVam == _IndexNoeVam0 || s.IndexNoeVam == _IndexNoeVam1).AsParallel();
                        List1 = new List<AazaSandogh>();
                        List2 = new List<AazaSandogh>();
                        List3 = new List<AazaSandogh>();
                        foreach (var item in q1)
                        {
                            //if (item.Code == 7000068)
                            //{
                            //    int a = 100;
                            //}
                            var q5 = q4.Where(f => f.HesabTafCode == item.Code);
                            decimal _SumBed = q5.Sum(f => f.Bed ?? 0);
                            decimal _SumBes = q5.Sum(f => f.Bes ?? 0);
                            decimal Mablagh = _SumBes - _SumBed;


                            DateTime dtNow = DateTime.Now;
                            int yyyy0 = Convert.ToInt32(dtNow.ToString().Substring(0, 4));
                            int MM0 = Convert.ToInt32(dtNow.ToString().Substring(5, 2));
                            int dd0 = Convert.ToInt32(dtNow.ToString().Substring(8, 2));
                            Mydate d0 = new Mydate(yyyy0, MM0, dd0);

                            // item.DaramadeMahiane = Mablagh;

                            var ho2 = db.HaghOzviats.Where(s => s.AazaId == item.AllTafId && s.Sarresid > dtNow).AsParallel();
                            if (ho2.Count() > 0)
                            {
                                item.DaramadeMahiane = Mablagh - ho2.Sum(s => s.Mablagh);

                            }
                            else
                            {
                                item.DaramadeMahiane = Mablagh;

                            }

                            if (q30.FirstOrDefault(s => s.AazaId == item.AllTafId) == null)
                            {
                                item.BirthDate = null;
                                item.TarikhTasviyeVam = item.TarikhOzviat;

                                item.SharhHesab = string.Empty;

                                int yyyy1 = Convert.ToInt32(item.TarikhOzviat.ToString().Substring(0, 4));
                                int MM1 = Convert.ToInt32(item.TarikhOzviat.ToString().Substring(5, 2));
                                int dd1 = Convert.ToInt32(item.TarikhOzviat.ToString().Substring(8, 2));
                                Mydate d1 = new Mydate(yyyy1, MM1, dd1);


                                int ModateEntezar = d1 - d0;
                                if (ModateEntezar > 0)
                                    item.CodeMelli = ModateEntezar.ToString();

                                var ho1 = ho.Where(s => s.AazaId == item.AllTafId && s.Sarresid <= dtNow).OrderBy(s => s.Tarikh).OrderBy(s => s.IndexMonth).ToList();
                                if (ho1.Count > 0)
                                {

                                    int Takhir = 0;
                                    int _Count = 0;
                                    //Mydate dt1 = new Mydate();
                                    for (int i = 0; i < ho1.Count; i++)
                                    {
                                        if (item.Code == 7000002)
                                        {
                                            int a = 100;
                                        }

                                        int yyyy2s = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(0, 4));
                                        int MM2s = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(5, 2));
                                        int dd2s = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(8, 2));
                                        Mydate d2s = new Mydate(yyyy2s, MM2s, dd2s);

                                        int yyyy2d = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(0, 4));
                                        int MM2d = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(5, 2));
                                        int dd2d = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(8, 2));
                                        Mydate d2d = new Mydate(yyyy2d, MM2d, dd2d);

                                        //if (d2s < d2d)
                                        //{
                                        //    item.TakhirVaTajil = (d2s - d2d) * -1;
                                        //}
                                        //else if (d2s > d2d)
                                        //{
                                        //    item.TakhirVaTajil = d2d - d2s;
                                        //}
                                        //else
                                        //{
                                        //    item.TakhirVaTajil = 0;
                                        //}


                                        //int yyyy2 = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(0, 4));
                                        //int MM2 = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(5, 2));
                                        //int dd2 = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(8, 2));
                                        //Mydate d2 = new Mydate(yyyy2, MM2, dd2);

                                        //int yyyy3 = ho1[i].Sal;
                                        //int MM3 = ho1[i].IndexMonth + 1;
                                        //int dd3 = dd1;

                                        //if (dd1 == 31)
                                        //{
                                        //    if (ho1[i].IndexMonth + 1 == 12)
                                        //    {
                                        //        //yyyy3 = yyyy3 + 1;
                                        //        //MM3 = 1;
                                        //        dd3 = 29;
                                        //    }
                                        //    else if (ho1[i].IndexMonth + 1 == 11 || ho1[i].IndexMonth + 1 == 10 || ho1[i].IndexMonth + 1 == 9 ||
                                        //        ho1[i].IndexMonth + 1 == 8 || ho1[i].IndexMonth + 1 == 7)
                                        //    {
                                        //        //yyyy3 = ho1[i].Sal;
                                        //        //MM3 = MM3 + 1;
                                        //        dd3 = 30;
                                        //    }
                                        //}
                                        //else if (dd1 == 30)
                                        //{
                                        //    if (ho1[i].IndexMonth + 1 == 12)
                                        //    {
                                        //        //yyyy3 = yyyy3 + 1;
                                        //        //MM3 = 1;
                                        //        dd3 = 29;
                                        //    }
                                        //}

                                        //Mydate d3 = new Mydate(yyyy3, MM3, dd3);
                                        if (d2s < d2d)
                                        {
                                            Takhir += (d2s - d2d) * -1;
                                            _Count++;
                                        }
                                        else if (d2s > d2d)
                                        {
                                            Takhir += d2d - d2s;
                                            _Count++;
                                        }

                                        if (i == ho1.Count - 1)
                                        {
                                            d2s.IncrementMonth();

                                            if (d2s < d0)
                                            {
                                                Takhir += (d2s - d0) * -1;
                                                _Count++;
                                            }
                                            //else if (d3 > d0 || d3 == d0)
                                            //{

                                            //}
                                        }
                                    }

                                    if (Takhir < 0)
                                    {

                                        item.CodePersoneli = (Takhir / _Count).ToString("n0");
                                    }
                                    else
                                    {
                                        item.CodePersoneli = "0";
                                    }
                                    item.TedadeFarzand = ModateEntezar - Convert.ToInt32(item.CodePersoneli.ToString().Replace("-", ""));
                                }
                                else
                                {
                                    item.CodePersoneli = (ModateEntezar * -1).ToString();
                                    item.TedadeFarzand = 0;
                                }


                                List1.Add(item);
                            }
                            else
                            {
                                var q301 = q30.Where(s => s.AazaId == item.AllTafId).OrderBy(s => s.Code);
                                var q302 = q301.Max(s => s.TarikhPardakht);
                                var q303 = q301.FirstOrDefault(s => s.TarikhPardakht == q302);

                                item.BirthDate = q303.TarikhPardakht;
                                item.TarikhTasviyeVam = q303.TarikhPardakht;

                                int yyyy1 = Convert.ToInt32(q302.ToString().Substring(0, 4));
                                int MM1 = Convert.ToInt32(q302.ToString().Substring(5, 2));
                                int dd1 = Convert.ToInt32(q302.ToString().Substring(8, 2));
                                Mydate d1 = new Mydate(yyyy1, MM1, dd1);


                                int ModateEntezar = d1 - d0;
                                if (ModateEntezar > 0)
                                    item.CodeMelli = ModateEntezar.ToString();
                                else
                                    item.CodeMelli = "0";

                                /////////////////////////////////محاسبه تأخیر در واریز پس انداز ماهیانه///////////////////////////////
                                int _Takhir1 = 0;
                                int _Count1 = 0;

                                var ho1 = ho.Where(s => s.AazaId == item.AllTafId && s.Sarresid >= q302 && s.Sarresid <= dtNow).OrderBy(s => s.Sarresid).ToList();
                                if (ho1.Count > 0)
                                {

                                    Mydate dt1 = new Mydate();
                                    for (int i = 0; i < ho1.Count; i++)
                                    {
                                        int yyyy2s = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(0, 4));
                                        int MM2s = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(5, 2));
                                        int dd2s = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(8, 2));
                                        Mydate d2s = new Mydate(yyyy2s, MM2s, dd2s);

                                        int yyyy2d = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(0, 4));
                                        int MM2d = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(5, 2));
                                        int dd2d = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(8, 2));
                                        Mydate d2d = new Mydate(yyyy2d, MM2d, dd2d);

                                        if (d2s < d2d)
                                        {
                                            _Takhir1 += (d2s - d2d) * -1;
                                            _Count1++;
                                        }
                                        else if (d2s > d2d)
                                        {
                                            _Takhir1 += d2d - d2s;
                                            _Count1++;
                                        }

                                        if (i == ho1.Count - 1)
                                        {
                                            d2s.IncrementMonth();

                                            if (d2s < d0)
                                            {
                                                _Takhir1 += (d2s - d0) * -1;
                                                _Count1++;
                                            }
                                            //else if (d3 > d0 || d3 == d0)
                                            //{

                                            //}
                                        }
                                    }

                                    //if (Takhir1 < 0)
                                    //{
                                    //    item.CodePersoneli = (Takhir1 / _Count1).ToString();
                                    //}
                                    //else
                                    //{
                                    //    item.CodePersoneli = "0";
                                    //}
                                    //item.TedadeFarzand = ModateEntezar + (Takhir / (ho1.Count + 1));
                                    //item.TedadeFarzand = Convert.ToInt32(item.CodeMelli) + Convert.ToInt32(item.CodePersoneli);

                                }
                                else
                                {
                                    //int yyyy2 = Convert.ToInt32(q302.ToString().Substring(0, 4));
                                    //int MM2 = Convert.ToInt32(q302.ToString().Substring(5, 2));
                                    int dd2 = Convert.ToInt32(item.TarikhOzviat.ToString().Substring(8, 2));
                                    int dd3 = dd2;

                                    if (dd2 == 31)
                                    {
                                        if (MM1 == 12)
                                        {
                                            //yyyy3 = yyyy3 + 1;
                                            //MM3 = 1;
                                            dd3 = 29;
                                        }
                                        else if (MM1 == 11 || MM1 == 10 || MM1 == 9 || MM1 == 8 || MM1 == 7)
                                        {
                                            //yyyy3 = ho1[i].Sal;
                                            //MM3 = MM3 + 1;
                                            dd3 = 30;
                                        }
                                    }
                                    else if (dd2 == 30)
                                    {
                                        if (MM1 == 12)
                                        {
                                            //yyyy3 = yyyy3 + 1;
                                            //MM3 = 1;
                                            dd3 = 29;
                                        }
                                    }

                                    Mydate d2 = new Mydate(yyyy1, MM1, dd3);

                                    if (d2 < d1 || d2 == d1)
                                    {
                                        d2.IncrementMonth();
                                    }

                                    if (d2 < d0)
                                    {
                                        _Takhir1 += (d2 - d0) * -1;
                                        _Count1++;

                                    }
                                    else if (d2 > d0)
                                    {
                                        _Takhir1 += (d0 - d2);
                                        _Count1++;

                                    }
                                    //item.CodePersoneli = ((d2 - d0) * -1).ToString();
                                    //else
                                    //    item.CodePersoneli = "0";

                                    //item.TedadeFarzand = Convert.ToInt32(item.CodeMelli) + Convert.ToInt32(item.CodePersoneli);
                                }


                                /////////////////////////////////////////////محاسبه تأخیر در واریز اقساط ماهیانه وام//////////////////////////////////////////////
                                int _Takhir2 = 0;
                                int _Count2 = 0;

                                if (q303.IsTasviye == true)
                                {
                                    item.SharhHesab = string.Empty;
                                    var ra = db.RizeAghsatVams.Where(s => s.AazaId == item.AllTafId && s.VamPardakhtiCode == q303.Code).OrderBy(s => s.TarikhSarresid).OrderBy(s => s.ShomareGhest).ToList();
                                    if (ra.Count > 0)
                                    {

                                        Mydate dt1 = new Mydate();
                                        for (int i = 0; i < ra.Count; i++)
                                        {

                                            int yyyy2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(0, 4));
                                            int MM2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(5, 2));
                                            int dd2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(8, 2));
                                            Mydate d2s = new Mydate(yyyy2s, MM2s, dd2s);

                                            int yyyy2d = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(0, 4));
                                            int MM2d = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(5, 2));
                                            int dd2d = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(8, 2));
                                            Mydate d2d = new Mydate(yyyy2d, MM2d, dd2d);

                                            //int yyyy2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(0, 4));
                                            //int MM2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(5, 2));
                                            //int dd2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(8, 2));
                                            //Mydate d2 = new Mydate(yyyy2, MM2, dd2);

                                            //int yyyy3 = ho1[i].Sal;
                                            //int MM3 = ho1[i].IndexMonth + 1;
                                            //int dd3 = dd1;

                                            //if (dd1 == 31)
                                            //{
                                            //    if (ho1[i].IndexMonth + 1 == 12)
                                            //    {
                                            //        yyyy3 = yyyy3 + 1;
                                            //        MM3 = 1;
                                            //        dd3 = 2;
                                            //    }
                                            //    else if (ho1[i].IndexMonth + 1 == 11 || ho1[i].IndexMonth + 1 == 10 || ho1[i].IndexMonth + 1 == 9 ||
                                            //        ho1[i].IndexMonth + 1 == 8 || ho1[i].IndexMonth + 1 == 7)
                                            //    {
                                            //        //yyyy3 = ho1[i].Sal;
                                            //        MM3 = MM3 + 1;
                                            //        dd3 = 1;
                                            //    }
                                            //}
                                            //else if (dd1 == 30)
                                            //{
                                            //    if (ho1[i].IndexMonth + 1 == 12)
                                            //    {
                                            //        yyyy3 = yyyy3 + 1;
                                            //        MM3 = 1;
                                            //        dd3 = 1;
                                            //    }
                                            //}

                                            //int yyyy3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(0, 4));
                                            //int MM3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(5, 2));
                                            //int dd3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(8, 2));
                                            //Mydate d3 = new Mydate(yyyy2, MM2, dd2);

                                            if (d2s < d2d)
                                            {
                                                _Takhir2 += (d2s - d2d) * -1;
                                                _Count2++;
                                            }
                                            else if (d2s > d2d)
                                            {
                                                _Takhir2 += d2d - d2s;
                                                _Count2++;
                                            }

                                            //if (i == ra.Count - 1)
                                            //{
                                            //    d2.IncrementMonth();

                                            //    if (d2 < d0)
                                            //    {
                                            //        Takhir += (d3 - d0) * -1;
                                            //        _Count++;
                                            //    }
                                            //    //else if (d3 > d0 || d3 == d0)
                                            //    //{

                                            //    //}
                                            //}
                                        }

                                        //if (Takhir2 < 0)
                                        //{
                                        //    item.CodePersoneli = (Convert.ToInt32(item.CodePersoneli) + Takhir2).ToString();
                                        //}
                                        //else
                                        //{
                                        //    item.CodePersoneli = "0";
                                        //}

                                        //item.TedadeFarzand = ModateEntezar + (Takhir2 / (ho1.Count + 1));

                                    }
                                    //else
                                    //{
                                    //    item.CodePersoneli = (ModateEntezar * -1).ToString();
                                    //    item.TedadeFarzand = 0;
                                    //}

                                    int _SumTakhir = _Takhir1 + _Takhir2;
                                    int _SumCount = _Count1 + _Count2;
                                    if (_SumTakhir < 0)
                                    {
                                        item.CodePersoneli = (_SumTakhir / _SumCount).ToString("n0");
                                    }
                                    else
                                    {
                                        item.CodePersoneli = "0";
                                    }
                                    item.TedadeFarzand = ModateEntezar - Convert.ToInt32(item.CodePersoneli.ToString().Replace("-", ""));

                                    List2.Add(item);
                                }
                                else
                                {
                                    item.SharhHesab = "تسویه نشده";
                                    var ra = db.RizeAghsatVams.Where(s => s.AazaId == item.AllTafId && s.VamPardakhtiCode == q303.Code && s.TarikhSarresid <= dtNow).OrderBy(s => s.TarikhSarresid).ToList();
                                    if (ra.Count > 0)
                                    {

                                        Mydate dt1 = new Mydate();
                                        for (int i = 0; i < ra.Count; i++)
                                        {

                                            int yyyy2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(0, 4));
                                            int MM2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(5, 2));
                                            int dd2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(8, 2));
                                            Mydate d2s = new Mydate(yyyy2s, MM2s, dd2s);

                                            int yyyy2d = ra[i].TarikhDaryaft != null ? Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(0, 4)) : Convert.ToInt32(dtNow.ToString().Substring(0, 4));
                                            int MM2d = ra[i].TarikhDaryaft != null ? Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(5, 2)) : Convert.ToInt32(dtNow.ToString().Substring(5, 2));
                                            int dd2d = ra[i].TarikhDaryaft != null ? Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(8, 2)) : Convert.ToInt32(dtNow.ToString().Substring(8, 2));
                                            Mydate d2d = new Mydate(yyyy2d, MM2d, dd2d);

                                            //int yyyy2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(0, 4));
                                            //int MM2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(5, 2));
                                            //int dd2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(8, 2));
                                            //Mydate d2 = new Mydate(yyyy2, MM2, dd2);

                                            //int yyyy3 = ho1[i].Sal;
                                            //int MM3 = ho1[i].IndexMonth + 1;
                                            //int dd3 = dd1;

                                            //if (dd1 == 31)
                                            //{
                                            //    if (ho1[i].IndexMonth + 1 == 12)
                                            //    {
                                            //        yyyy3 = yyyy3 + 1;
                                            //        MM3 = 1;
                                            //        dd3 = 2;
                                            //    }
                                            //    else if (ho1[i].IndexMonth + 1 == 11 || ho1[i].IndexMonth + 1 == 10 || ho1[i].IndexMonth + 1 == 9 ||
                                            //        ho1[i].IndexMonth + 1 == 8 || ho1[i].IndexMonth + 1 == 7)
                                            //    {
                                            //        //yyyy3 = ho1[i].Sal;
                                            //        MM3 = MM3 + 1;
                                            //        dd3 = 1;
                                            //    }
                                            //}
                                            //else if (dd1 == 30)
                                            //{
                                            //    if (ho1[i].IndexMonth + 1 == 12)
                                            //    {
                                            //        yyyy3 = yyyy3 + 1;
                                            //        MM3 = 1;
                                            //        dd3 = 1;
                                            //    }
                                            //}

                                            //int yyyy3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(0, 4));
                                            //int MM3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(5, 2));
                                            //int dd3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(8, 2));
                                            //Mydate d3 = new Mydate(yyyy2, MM2, dd2);

                                            if (d2s < d2d)
                                            {
                                                _Takhir2 += (d2s - d2d) * -1;
                                                _Count2++;
                                            }
                                            else if (d2s > d2d)
                                            {
                                                _Takhir2 += d2d - d2s;
                                                _Count2++;
                                            }

                                            //if (i == ra.Count - 1)
                                            //{
                                            //    d2.IncrementMonth();

                                            //    if (d2 < d0)
                                            //    {
                                            //        Takhir += (d3 - d0) * -1;
                                            //        _Count++;
                                            //    }
                                            //    //else if (d3 > d0 || d3 == d0)
                                            //    //{

                                            //    //}
                                            //}
                                        }

                                        //if (Takhir2 < 0)
                                        //{
                                        //    item.CodePersoneli = (Convert.ToInt32(item.CodePersoneli) + Takhir2).ToString();
                                        //}
                                        //else
                                        //{
                                        //    item.CodePersoneli = "0";
                                        //}

                                        //item.TedadeFarzand = ModateEntezar + (Takhir2 / (ho1.Count + 1));

                                    }
                                    //else
                                    //{
                                    //    item.CodePersoneli = (ModateEntezar * -1).ToString();
                                    //    item.TedadeFarzand = 0;
                                    //}

                                    int _SumTakhir = _Takhir1 + _Takhir2;
                                    int _SumCount = _Count1 + _Count2;
                                    if (_SumTakhir < 0)
                                    {
                                        item.CodePersoneli = (_SumTakhir / _SumCount).ToString("n0");
                                    }
                                    else
                                    {
                                        item.CodePersoneli = "0";
                                    }
                                    item.TedadeFarzand = ModateEntezar - Convert.ToInt32(item.CodePersoneli.ToString().Replace("-", ""));

                                    List3.Add(item);
                                }
                            }
                        }

                        xtraTabControl2_SelectedPageChanged(null, null);
                    }

                    SplashScreenManager.CloseForm();

                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }

        private void btnDesignReport_Click(object sender, EventArgs e)
        {

        }

        private void btnPrintPreview_Click(object sender, EventArgs e)
        {

        }

        private void gridView1_CustomDrawRowIndicator(object sender, DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs e)
        {
            HelpClass1.CustomDrawRowIndicator(sender, e, gridView1);
        }

        private void gridView2_CustomDrawRowIndicator(object sender, DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs e)
        {
            HelpClass1.CustomDrawRowIndicator(sender, e, gridView2);
        }

        private void FrmNobatVam_Load(object sender, EventArgs e)
        {
            _IDSandogh = Convert.ToInt32(Fm.IDSandogh.Caption);

            using (var db = new MyContext())
            {
                try
                {
                    var q = db.Tanzimats.FirstOrDefault(s => s.SandoghId == _IDSandogh);
                    //cmbNoeVam.SelectedIndex = q;

                    if (q.checkEdit6)
                    {
                        //checkEdit1.Checked = q.AnvaeVams.FirstOrDefault(s => s.NoeVamIndex == 0).DefaultNoeVam;
                        //checkEdit2.Checked = q.AnvaeVams.FirstOrDefault(s => s.NoeVamIndex == 1).DefaultNoeVam;
                        //checkEdit3.Checked = q.AnvaeVams.FirstOrDefault(s => s.NoeVamIndex == 2).DefaultNoeVam;
                        //checkEdit4.Checked = q.AnvaeVams.FirstOrDefault(s => s.NoeVamIndex == 3).DefaultNoeVam;

                        checkEdit1.Checked = true;
                        checkEdit2.Checked = true;
                        checkEdit3.Checked = false;
                        checkEdit4.Checked = false;

                        checkEdit1.Text = q.AnvaeVams.FirstOrDefault(s => s.NoeVamIndex == 0).NoeVamName;
                        checkEdit2.Text = q.AnvaeVams.FirstOrDefault(s => s.NoeVamIndex == 1).NoeVamName;
                        checkEdit3.Text = q.AnvaeVams.FirstOrDefault(s => s.NoeVamIndex == 2).NoeVamName;
                        checkEdit4.Text = q.AnvaeVams.FirstOrDefault(s => s.NoeVamIndex == 3).NoeVamName;
                        if (q.NoeRezervIndex == 0)
                        {

                            xtraTabControl1.SelectedTabPageIndex = 0;
                            xtraTabControl1.TabPages[1].PageVisible = false;
                            xtraTabControl1.TabPages[2].PageVisible = false;
                            xtraTabControl1.TabPages[3].PageVisible = false;
                            xtraTabControl1.TabPages[0].Text = "نوبت بندی براساس تاریخ عضویت اعضاء در صندوق";
                        }
                        else if (q.NoeRezervIndex == 1)
                        {
                            xtraTabControl1.SelectedTabPageIndex = 1;
                            xtraTabControl1.TabPages[0].PageVisible = false;
                            xtraTabControl1.TabPages[2].PageVisible = false;
                            xtraTabControl1.TabPages[3].PageVisible = false;
                            xtraTabControl1.TabPages[1].Text = "نوبت بندی براساس شماره نوبت اعضاء در صندوق";

                        }
                        else if (q.NoeRezervIndex == 2)
                        {
                            xtraTabControl1.SelectedTabPageIndex = 2;
                            xtraTabControl1.TabPages[0].PageVisible = false;
                            xtraTabControl1.TabPages[1].PageVisible = false;
                            xtraTabControl1.TabPages[3].PageVisible = false;
                            xtraTabControl1.TabPages[2].Text = "نوبت بندی براساس تاریخ عضویت اعضاء جدید صندوق و تاریخ تسویه وام قبلی اعضاء قدیم";
                            //labelControl21.Visible = true;
                        }
                        else if (q.NoeRezervIndex == 3)
                        {
                            //checkEdit1.Checked = true;
                            //checkEdit2.Checked = true;
                            //checkEdit3.Checked = false;
                            //checkEdit4.Checked = false;
                            checkEdit1.Visible = true;
                            checkEdit2.Visible = true;
                            checkEdit3.Visible = false;
                            checkEdit4.Visible = false;
                            checkEdit1.ReadOnly = true;
                            checkEdit2.ReadOnly = true;
                            checkEdit3.ReadOnly = true;
                            checkEdit4.ReadOnly = true;

                            xtraTabControl1.SelectedTabPageIndex = 3;
                            xtraTabControl1.TabPages[0].PageVisible = false;
                            xtraTabControl1.TabPages[1].PageVisible = false;
                            xtraTabControl1.TabPages[2].PageVisible = false;
                            xtraTabControl1.TabPages[3].Text = "نوبت بندی بر اساس تاریخ عضویت اعضاء جدید صندوق و تاریخ پرداخت وام به اعضاء قدیم";
                            //labelControl21.Visible = true;
                        }
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }

        private void gridView3_CustomDrawRowIndicator(object sender, DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs e)
        {
            HelpClass1.CustomDrawRowIndicator(sender, e, gridView3);

        }

        private void gridView2_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Control && e.KeyCode == Keys.E)
            {
                HelpClass1.ExportDataGridViewToExcel(this, gridView2, gridView2.RowCount);
            }

        }

        private void gridView1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Control && e.KeyCode == Keys.E)
            {
                HelpClass1.ExportDataGridViewToExcel(this, gridView1, gridView1.RowCount);
            }

        }

        private void gridView3_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Control && e.KeyCode == Keys.E)
            {
                HelpClass1.ExportDataGridViewToExcel(this, gridView3, gridView3.RowCount);
            }

        }

        private void xtraTabControl1_SelectedPageChanged(object sender, DevExpress.XtraTab.TabPageChangedEventArgs e)
        {
            panelControl1.Height = xtraTabControl1.SelectedTabPageIndex == 2 ? 80 : 50;
            labelControl21.Visible = xtraTabControl1.SelectedTabPageIndex == 2 ? true : false;
            labelControl5.Visible = xtraTabControl1.SelectedTabPageIndex == 3 ? true : false; ;
        }

        private void gridView4_CustomDrawRowIndicator(object sender, DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs e)
        {
            GridView view = sender as GridView;
            HelpClass1.CustomDrawRowIndicator(sender, e, view);

        }

        private void gridView5_CustomDrawRowIndicator(object sender, RowIndicatorCustomDrawEventArgs e)
        {
            GridView view = sender as GridView;
            HelpClass1.CustomDrawRowIndicator(sender, e, view);

        }

        private void gridView6_CustomDrawRowIndicator(object sender, RowIndicatorCustomDrawEventArgs e)
        {
            GridView view = sender as GridView;
            HelpClass1.CustomDrawRowIndicator(sender, e, view);

        }

        private void gridView6_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Control && e.KeyCode == Keys.E)
            {
                HelpClass1.ExportDataGridViewToExcel(this, gridView6, gridView6.RowCount);
            }

        }

        private void gridView5_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Control && e.KeyCode == Keys.E)
            {
                HelpClass1.ExportDataGridViewToExcel(this, gridView5, gridView5.RowCount);
            }

        }

        private void gridView4_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Control && e.KeyCode == Keys.E)
            {
                HelpClass1.ExportDataGridViewToExcel(this, gridView4, gridView4.RowCount);
            }

        }

        private void gridView0_DoubleClick(object sender, EventArgs e)
        {
            using (var db = new MyContext())
            {
                try
                {
                    _IndexNoeVam0 = checkEdit1.Checked ? 0 : -1;
                    _IndexNoeVam1 = checkEdit2.Checked ? 1 : -1;
                    _IndexNoeVam2 = checkEdit3.Checked ? 2 : -1;
                    _IndexNoeVam3 = checkEdit4.Checked ? 3 : -1;

                    GridView view = sender as GridView;

                    int _Code = Convert.ToInt32(view.GetFocusedRowCellValue("Code").ToString());
                    var q1 = db.AazaSandoghs.FirstOrDefault(s => s.IsActive == true && s.Code == _Code);
                    //var q2 = db.VamPardakhtis.Where(s => s.AllHesabTafzili1.GroupTafziliId == 3 && s.AllHesabTafzili1.Code == _Code).AsParallel();
                    //var q4 = db.AsnadeHesabdariRows.Where(f => f.HesabMoinCode == 7001 && f.HesabTafCode == _Code).AsParallel();
                    //var ho = db.HaghOzviats.AsParallel();

                    List<AazaSandogh> List = new List<AazaSandogh>();
                    //var q3 = q2.Where(s => s.IsTasviye == false && (s.IndexNoeVam == _IndexNoeVam0 || s.IndexNoeVam == _IndexNoeVam1 || s.IndexNoeVam == _IndexNoeVam2 || s.IndexNoeVam == _IndexNoeVam3)).AsParallel();



                    List<AazaSandogh> List01 = new List<AazaSandogh>();
                    List<AazaSandogh> List02 = new List<AazaSandogh>();
                    List<AazaSandogh> List03 = new List<AazaSandogh>();
                    int _Takhir = 0;
                    int _Count = 0;
                    int _Takhir1 = 0;
                    int _Count1 = 0;
                    int _Takhir2 = 0;
                    int _Count2 = 0;

                    if (q1 != null)
                    {
                        //if (q1.Code == 7000068)
                        //{
                        //    int a = 100;
                        //}
                        //var q5 = q4.Where(f => f.HesabTafCode == q1.Code);
                        //decimal _SumBed = q5.Sum(f => f.Bed ?? 0);
                        //decimal _SumBes = q5.Sum(f => f.Bes ?? 0);
                        //decimal Mablagh = _SumBes - _SumBed;

                        AazaSandogh obj1;
                        DateTime dtNow = DateTime.Now;
                        int yyyy0 = Convert.ToInt32(dtNow.ToString().Substring(0, 4));
                        int MM0 = Convert.ToInt32(dtNow.ToString().Substring(5, 2));
                        int dd0 = Convert.ToInt32(dtNow.ToString().Substring(8, 2));
                        Mydate d0 = new Mydate(yyyy0, MM0, dd0);

                        // q1.DaramadeMahiane = Mablagh;

                        //var ho2 = db.HaghOzviats.Where(s => s.AazaId == q1.AllTafId && s.Sarresid > dtNow).AsParallel();
                        //if (ho2.Count() > 0)
                        //{
                        //    q1.DaramadeMahiane = Mablagh - ho2.Sum(s => s.Mablagh);

                        //}
                        //else
                        //{
                        //    q1.DaramadeMahiane = Mablagh;

                        //}

                        var q30 = db.VamPardakhtis.Where(s => s.AazaId == q1.AllTafId && (s.IndexNoeVam == _IndexNoeVam0 || s.IndexNoeVam == _IndexNoeVam1)).ToList();
                        if (q30.Count == 0)
                        {



                            //int ModateEntezar = d1 - d0;
                            //if (ModateEntezar > 0)
                            // q1.CodeMelli = ModateEntezar.ToString();

                            var ho1 = db.HaghOzviats.Where(s => s.AazaId == q1.AllTafId && s.Sarresid <= dtNow).OrderBy(s => s.Tarikh).OrderBy(s => s.IndexMonth).ToList();
                            if (ho1.Count > 0)
                            {

                                //Mydate dt1 = new Mydate();
                                for (int i = 0; i < ho1.Count; i++)
                                {
                                    obj1 = new AazaSandogh();

                                    obj1.Code = q1.Code;
                                    obj1.NameVFamil = q1.NameVFamil;
                                    obj1.TarikhOzviat = ho1[i].Sarresid;
                                    obj1.BirthDate = ho1[i].Tarikh;
                                    //q1.TarikhTasviyeVam = q1.TarikhOzviat;

                                    obj1.SharhHesab = "پس انداز ماهیانه";

                                    int yyyy1 = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(0, 4));
                                    int MM1 = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(5, 2));
                                    int dd1 = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(8, 2));
                                    Mydate d1s = new Mydate(yyyy1, MM1, dd1);

                                    int yyyy2 = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(0, 4));
                                    int MM2 = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(5, 2));
                                    int dd2 = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(8, 2));
                                    Mydate d2d = new Mydate(yyyy2, MM2, dd2);

                                    //int yyyy3 = ho1[i].Sal;
                                    //int MM3 = ho1[i].IndexMonth + 1;
                                    //int dd3 = dd1;

                                    //if (dd1 == 31)
                                    //{
                                    //    if (ho1[i].IndexMonth + 1 == 12)
                                    //    {
                                    //        //yyyy3 = yyyy3 + 1;
                                    //        //MM3 = 1;
                                    //        dd3 = 29;
                                    //    }
                                    //    else if (ho1[i].IndexMonth + 1 == 11 || ho1[i].IndexMonth + 1 == 10 || ho1[i].IndexMonth + 1 == 9 ||
                                    //        ho1[i].IndexMonth + 1 == 8 || ho1[i].IndexMonth + 1 == 7)
                                    //    {
                                    //        //yyyy3 = ho1[i].Sal;
                                    //        //MM3 = MM3 + 1;
                                    //        dd3 = 30;
                                    //    }
                                    //}
                                    //else if (dd1 == 30)
                                    //{
                                    //    if (ho1[i].IndexMonth + 1 == 12)
                                    //    {
                                    //        //yyyy3 = yyyy3 + 1;
                                    //        //MM3 = 1;
                                    //        dd3 = 29;
                                    //    }
                                    //}

                                    //Mydate d3 = new Mydate(yyyy3, MM3, dd3);
                                    if (d1s < d2d)
                                    {
                                        _Takhir += (d1s - d2d) * -1;
                                        _Count++;
                                        obj1.TedadeFarzand = (d1s - d2d) * -1;
                                    }
                                    else if (d1s > d2d)
                                    {
                                        _Takhir += d2d - d1s;
                                        _Count++;
                                        obj1.TedadeFarzand = d2d - d1s;
                                    }
                                    else
                                    {
                                        obj1.TedadeFarzand = 0;
                                    }

                                    List01.Add(obj1);

                                    if (i == ho1.Count - 1)
                                    {
                                        d1s.IncrementMonth();

                                        if (d1s < d0)
                                        {
                                            _Takhir += (d1s - d0) * -1;
                                            _Count++;

                                            //var q2 = db.AazaSandoghs.FirstOrDefault(s => s.IsActive == true && s.Code == _Code);
                                            obj1 = new AazaSandogh();
                                            obj1.Code = q1.Code;
                                            obj1.NameVFamil = q1.NameVFamil;
                                            obj1.SharhHesab = "پس انداز ماهيانه";
                                            obj1.TarikhOzviat = Convert.ToDateTime(d1s);
                                            obj1.BirthDate = Convert.ToDateTime(d0);
                                            obj1.TedadeFarzand = (d1s - d0) * -1;
                                            List01.Add(obj1);
                                        }
                                    }
                                }

                                //if (Takhir < 0)
                                //{
                                //    q1.CodePersoneli = (Takhir / _Count).ToString();
                                //}
                                //else
                                //{
                                //    q1.CodePersoneli = "0";
                                //}
                                //q1.TedadeFarzand = ModateEntezar + Convert.ToInt32(q1.CodePersoneli);
                            }
                            else
                            {
                                int yyyy1 = Convert.ToInt32(q1.TarikhOzviat.ToString().Substring(0, 4));
                                int MM1 = Convert.ToInt32(q1.TarikhOzviat.ToString().Substring(5, 2));
                                int dd1 = Convert.ToInt32(q1.TarikhOzviat.ToString().Substring(8, 2));
                                Mydate d1s = new Mydate(yyyy1, MM1, dd1);

                                if (d1s < d0)
                                {
                                    _Takhir += (d1s - d0) * -1;
                                    _Count++;

                                    q1.SharhHesab = "پس انداز ماهيانه";
                                    q1.TarikhOzviat = Convert.ToDateTime(d1s);
                                    q1.BirthDate = Convert.ToDateTime(d0);
                                    q1.TedadeFarzand = (d1s - d0) * -1;
                                    List01.Add(q1);
                                }
                            }


                            //List1.Add(item);
                        }
                        else
                        {
                            var q301 = q30.Where(s => s.AazaId == q1.AllTafId).OrderBy(s => s.Code);
                            var q302 = q301.Max(s => s.TarikhPardakht);
                            var q303 = q301.FirstOrDefault(s => s.TarikhPardakht == q302);

                            //q1.BirthDate = q303.TarikhPardakht;
                            //q1.TarikhTasviyeVam = q303.TarikhPardakht;

                            int yyyy1pv = Convert.ToInt32(q302.ToString().Substring(0, 4));
                            int MM1pv = Convert.ToInt32(q302.ToString().Substring(5, 2));
                            int dd1pv = Convert.ToInt32(q302.ToString().Substring(8, 2));
                            Mydate d1pv = new Mydate(yyyy1pv, MM1pv, dd1pv);


                            //int ModateEntezar = d1pv - d0;
                            //if (ModateEntezar > 0)
                            //q1.CodeMelli = ModateEntezar.ToString();
                            //else
                            //q1.CodeMelli = "0";

                            /////////////////////////////////محاسبه تأخیر در واریز پس انداز ماهیانه///////////////////////////////

                            var ho1 = db.HaghOzviats.Where(s => s.AazaId == q1.AllTafId && s.Sarresid >= q302 && s.Sarresid <= dtNow).OrderBy(s => s.Sarresid).ToList();
                            if (ho1.Count > 0)
                            {

                                //Mydate dt1 = new Mydate();
                                for (int i = 0; i < ho1.Count; i++)
                                {
                                    obj1 = new AazaSandogh();

                                    obj1.Code = q1.Code;
                                    obj1.NameVFamil = q1.NameVFamil;
                                    obj1.TarikhOzviat = ho1[i].Sarresid;
                                    obj1.BirthDate = ho1[i].Tarikh;
                                    //q1.TarikhTasviyeVam = q1.TarikhOzviat;

                                    obj1.SharhHesab = "پس انداز ماهیانه";

                                    int yyyy2s = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(0, 4));
                                    int MM2s = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(5, 2));
                                    int dd2s = Convert.ToInt32(ho1[i].Sarresid.ToString().Substring(8, 2));
                                    Mydate d2s = new Mydate(yyyy2s, MM2s, dd2s);

                                    int yyyy2d = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(0, 4));
                                    int MM2d = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(5, 2));
                                    int dd2d = Convert.ToInt32(ho1[i].Tarikh.ToString().Substring(8, 2));
                                    Mydate d2d = new Mydate(yyyy2d, MM2d, dd2d);

                                    if (d2s < d2d)
                                    {
                                        _Takhir1 += (d2s - d2d) * -1;
                                        _Count1++;
                                        obj1.TedadeFarzand = (d2s - d2d) * -1;

                                    }
                                    else if (d2s > d2d)
                                    {
                                        _Takhir1 += d2d - d2s;
                                        _Count1++;
                                        obj1.TedadeFarzand = d2d - d2s;

                                    }
                                    else
                                    {
                                        obj1.TedadeFarzand = 0;
                                    }

                                    List02.Add(obj1);

                                    if (i == ho1.Count - 1)
                                    {
                                        d2s.IncrementMonth();

                                        if (d2s < d0)
                                        {
                                            _Takhir1 += (d2s - d0) * -1;
                                            _Count1++;

                                            obj1 = new AazaSandogh();
                                            obj1.Code = q1.Code;
                                            obj1.NameVFamil = q1.NameVFamil;
                                            obj1.SharhHesab = "پس انداز ماهيانه";
                                            obj1.TarikhOzviat = Convert.ToDateTime(d2s);
                                            obj1.BirthDate = Convert.ToDateTime(d0);
                                            obj1.TedadeFarzand = (d2s - d0) * -1;
                                            List02.Add(obj1);
                                        }
                                        //else if (d3 > d0 || d3 == d0)
                                        //{

                                        //}
                                    }
                                }

                                //if (Takhir1 < 0)
                                //{
                                //    q1.CodePersoneli = (Takhir1 / _Count1).ToString();
                                //}
                                //else
                                //{
                                //    q1.CodePersoneli = "0";
                                //}
                                //q1.TedadeFarzand = ModateEntezar + (Takhir / (ho1.Count + 1));
                                //q1.TedadeFarzand = Convert.ToInt32(q1.CodeMelli) + Convert.ToInt32(q1.CodePersoneli);

                            }
                            else
                            {
                                //int yyyy2 = Convert.ToInt32(q302.ToString().Substring(0, 4));
                                //int MM2 = Convert.ToInt32(q302.ToString().Substring(5, 2));
                                int dd2to = Convert.ToInt32(q1.TarikhOzviat.ToString().Substring(8, 2));
                                int dd3to = dd2to;

                                if (dd2to == 31)
                                {
                                    if (MM1pv == 12)
                                    {
                                        //yyyy3 = yyyy3 + 1;
                                        //MM3 = 1;
                                        dd3to = 29;
                                    }
                                    else if (MM1pv == 11 || MM1pv == 10 || MM1pv == 9 || MM1pv == 8 || MM1pv == 7)
                                    {
                                        //yyyy3 = ho1[i].Sal;
                                        //MM3 = MM3 + 1;
                                        dd3to = 30;
                                    }
                                }
                                else if (dd2to == 30)
                                {
                                    if (MM1pv == 12)
                                    {
                                        //yyyy3 = yyyy3 + 1;
                                        //MM3 = 1;
                                        dd3to = 29;
                                    }
                                }

                                Mydate d2to = new Mydate(yyyy1pv, MM1pv, dd3to);

                                if (d2to < d1pv || d2to == d1pv)
                                {
                                    d2to.IncrementMonth();
                                }

                                if (d2to < d0)
                                {
                                    _Takhir1 += (d2to - d0) * -1;
                                    _Count1++;

                                    q1.SharhHesab = "پس انداز ماهيانه";
                                    q1.TarikhOzviat = Convert.ToDateTime(d2to);
                                    q1.BirthDate = Convert.ToDateTime(d0);
                                    q1.TedadeFarzand = (d2to - d0) * -1;
                                    List02.Add(q1);

                                }
                                //else if (d2to > d0)
                                //{
                                //    _Takhir1 += d0 - d2to;
                                //    _Count1++;

                                //}
                                //q1.CodePersoneli = ((d2 - d0) * -1).ToString();
                                //else
                                //    q1.CodePersoneli = "0";

                                //q1.TedadeFarzand = Convert.ToInt32(q1.CodeMelli) + Convert.ToInt32(q1.CodePersoneli);
                            }


                            /////////////////////////////////////////////محاسبه تأخیر در واریز اقساط ماهیانه وام//////////////////////////////////////////////

                            if (q303.IsTasviye == true)
                            {
                                var ra = db.RizeAghsatVams.Where(s => s.AazaId == q1.AllTafId && s.VamPardakhtiCode == q303.Code).OrderBy(s => s.TarikhSarresid).ToList();
                                if (ra.Count > 0)
                                {
                                    //Mydate dt1 = new Mydate();
                                    for (int i = 0; i < ra.Count; i++)
                                    {
                                        obj1 = new AazaSandogh();

                                        obj1.Code = q1.Code;
                                        obj1.NameVFamil = q1.NameVFamil;
                                        //q1.TarikhTasviyeVam = q1.TarikhOzviat;
                                        obj1.SharhHesab = "اقساط ماهیانه";

                                        int yyyy2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(0, 4));
                                        int MM2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(5, 2));
                                        int dd2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(8, 2));
                                        Mydate d2s = new Mydate(yyyy2s, MM2s, dd2s);

                                        int yyyy2d = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(0, 4));
                                        int MM2d = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(5, 2));
                                        int dd2d = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(8, 2));
                                        Mydate d2d = new Mydate(yyyy2d, MM2d, dd2d);

                                        obj1.TarikhOzviat = ra[i].TarikhSarresid;
                                        obj1.BirthDate = ra[i].TarikhDaryaft;


                                        //int yyyy2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(0, 4));
                                        //int MM2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(5, 2));
                                        //int dd2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(8, 2));
                                        //Mydate d2 = new Mydate(yyyy2, MM2, dd2);

                                        //int yyyy3 = ho1[i].Sal;
                                        //int MM3 = ho1[i].IndexMonth + 1;
                                        //int dd3 = dd1;

                                        //if (dd1 == 31)
                                        //{
                                        //    if (ho1[i].IndexMonth + 1 == 12)
                                        //    {
                                        //        yyyy3 = yyyy3 + 1;
                                        //        MM3 = 1;
                                        //        dd3 = 2;
                                        //    }
                                        //    else if (ho1[i].IndexMonth + 1 == 11 || ho1[i].IndexMonth + 1 == 10 || ho1[i].IndexMonth + 1 == 9 ||
                                        //        ho1[i].IndexMonth + 1 == 8 || ho1[i].IndexMonth + 1 == 7)
                                        //    {
                                        //        //yyyy3 = ho1[i].Sal;
                                        //        MM3 = MM3 + 1;
                                        //        dd3 = 1;
                                        //    }
                                        //}
                                        //else if (dd1 == 30)
                                        //{
                                        //    if (ho1[i].IndexMonth + 1 == 12)
                                        //    {
                                        //        yyyy3 = yyyy3 + 1;
                                        //        MM3 = 1;
                                        //        dd3 = 1;
                                        //    }
                                        //}

                                        //int yyyy3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(0, 4));
                                        //int MM3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(5, 2));
                                        //int dd3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(8, 2));
                                        //Mydate d3 = new Mydate(yyyy2, MM2, dd2);

                                        if (d2s < d2d)
                                        {
                                            _Takhir2 += (d2s - d2d) * -1;
                                            _Count2++;
                                            obj1.TedadeFarzand = (d2s - d2d) * -1;

                                        }
                                        else if (d2s > d2d)
                                        {
                                            _Takhir2 += d2d - d2s;
                                            _Count2++;
                                            obj1.TedadeFarzand = d2d - d2s;

                                        }
                                        else
                                        {
                                            obj1.TedadeFarzand = 0;
                                        }
                                        List02.Add(obj1);

                                        //if (i == ra.Count - 1)
                                        //{
                                        //    d2.IncrementMonth();

                                        //    if (d2 < d0)
                                        //    {
                                        //        Takhir += (d3 - d0) * -1;
                                        //        _Count++;
                                        //    }
                                        //    //else if (d3 > d0 || d3 == d0)
                                        //    //{

                                        //    //}
                                        //}
                                    }

                                    //if (Takhir2 < 0)
                                    //{
                                    //    q1.CodePersoneli = (Convert.ToInt32(q1.CodePersoneli) + Takhir2).ToString();
                                    //}
                                    //else
                                    //{
                                    //    q1.CodePersoneli = "0";
                                    //}

                                    //q1.TedadeFarzand = ModateEntezar + (Takhir2 / (ho1.Count + 1));

                                }
                                //else
                                //{
                                //    q1.CodePersoneli = (ModateEntezar * -1).ToString();
                                //    q1.TedadeFarzand = 0;
                                //}

                                //int _SumTakhir = _Takhir1 + _Takhir2;
                                //int _SumCount = _Count1 + _Count2;
                                //if (_SumTakhir < 0)
                                //{
                                //    q1.CodePersoneli = (_SumTakhir / _SumCount).ToString();
                                //}
                                //else
                                //{
                                //    q1.CodePersoneli = "0";
                                //}
                                //q1.TedadeFarzand = ModateEntezar + Convert.ToInt32(q1.CodePersoneli);

                                //List2.Add(item);
                            }
                            else
                            {

                                var ra = db.RizeAghsatVams.Where(s => s.AazaId == q1.AllTafId && s.VamPardakhtiCode == q303.Code && s.TarikhSarresid <= dtNow).OrderBy(s => s.TarikhSarresid).ToList();
                                if (ra.Count > 0)
                                {
                                    //Mydate dt1 = new Mydate();
                                    for (int i = 0; i < ra.Count; i++)
                                    {
                                        obj1 = new AazaSandogh();

                                        obj1.Code = q1.Code;
                                        obj1.NameVFamil = q1.NameVFamil;
                                        //q1.TarikhTasviyeVam = q1.TarikhOzviat;
                                        obj1.SharhHesab = "اقساط ماهیانه";

                                        int yyyy2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(0, 4));
                                        int MM2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(5, 2));
                                        int dd2s = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(8, 2));
                                        Mydate d2s = new Mydate(yyyy2s, MM2s, dd2s);

                                        int yyyy2d = ra[i].TarikhDaryaft != null ? Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(0, 4)) : Convert.ToInt32(dtNow.ToString().Substring(0, 4));
                                        int MM2d = ra[i].TarikhDaryaft != null ? Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(5, 2)) : Convert.ToInt32(dtNow.ToString().Substring(5, 2));
                                        int dd2d = ra[i].TarikhDaryaft != null ? Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(8, 2)) : Convert.ToInt32(dtNow.ToString().Substring(8, 2));
                                        Mydate d2d = new Mydate(yyyy2d, MM2d, dd2d);

                                        obj1.TarikhOzviat = ra[i].TarikhSarresid;
                                        obj1.BirthDate = ra[i].TarikhDaryaft;

                                        //int yyyy2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(0, 4));
                                        //int MM2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(5, 2));
                                        //int dd2 = Convert.ToInt32(ra[i].TarikhSarresid.ToString().Substring(8, 2));
                                        //Mydate d2 = new Mydate(yyyy2, MM2, dd2);

                                        //int yyyy3 = ho1[i].Sal;
                                        //int MM3 = ho1[i].IndexMonth + 1;
                                        //int dd3 = dd1;

                                        //if (dd1 == 31)
                                        //{
                                        //    if (ho1[i].IndexMonth + 1 == 12)
                                        //    {
                                        //        yyyy3 = yyyy3 + 1;
                                        //        MM3 = 1;
                                        //        dd3 = 2;
                                        //    }
                                        //    else if (ho1[i].IndexMonth + 1 == 11 || ho1[i].IndexMonth + 1 == 10 || ho1[i].IndexMonth + 1 == 9 ||
                                        //        ho1[i].IndexMonth + 1 == 8 || ho1[i].IndexMonth + 1 == 7)
                                        //    {
                                        //        //yyyy3 = ho1[i].Sal;
                                        //        MM3 = MM3 + 1;
                                        //        dd3 = 1;
                                        //    }
                                        //}
                                        //else if (dd1 == 30)
                                        //{
                                        //    if (ho1[i].IndexMonth + 1 == 12)
                                        //    {
                                        //        yyyy3 = yyyy3 + 1;
                                        //        MM3 = 1;
                                        //        dd3 = 1;
                                        //    }
                                        //}

                                        //int yyyy3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(0, 4));
                                        //int MM3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(5, 2));
                                        //int dd3 = Convert.ToInt32(ra[i].TarikhDaryaft.ToString().Substring(8, 2));
                                        //Mydate d3 = new Mydate(yyyy2, MM2, dd2);

                                        if (d2s < d2d)
                                        {
                                            _Takhir2 += (d2s - d2d) * -1;
                                            _Count2++;
                                            obj1.TedadeFarzand = (d2s - d2d) * -1;

                                        }
                                        else if (d2s > d2d)
                                        {
                                            _Takhir2 += d2d - d2s;
                                            _Count2++;
                                            obj1.TedadeFarzand = d2d - d2s; ;

                                        }
                                        else
                                        {
                                            obj1.TedadeFarzand = 0;
                                        }


                                        List03.Add(obj1);
                                        //if (i == ra.Count - 1)
                                        //{
                                        //    d2.IncrementMonth();

                                        //    if (d2 < d0)
                                        //    {
                                        //        Takhir += (d3 - d0) * -1;
                                        //        _Count++;
                                        //    }
                                        //    //else if (d3 > d0 || d3 == d0)
                                        //    //{

                                        //    //}
                                        //}
                                    }

                                    //if (Takhir2 < 0)
                                    //{
                                    //    q1.CodePersoneli = (Convert.ToInt32(q1.CodePersoneli) + Takhir2).ToString();
                                    //}
                                    //else
                                    //{
                                    //    q1.CodePersoneli = "0";
                                    //}

                                    //q1.TedadeFarzand = ModateEntezar + (Takhir2 / (ho1.Count + 1));

                                }
                                //else
                                //{
                                //    q1.CodePersoneli = (ModateEntezar * -1).ToString();
                                //    q1.TedadeFarzand = 0;
                                //}

                                //int _SumTakhir = _Takhir1 + _Takhir2;
                                //int _SumCount = _Count1 + _Count2;
                                //if (_SumTakhir < 0)
                                //{
                                //    q1.CodePersoneli = (_SumTakhir / _SumCount).ToString();
                                //}
                                //else
                                //{
                                //    q1.CodePersoneli = "0";
                                //}
                                //q1.TedadeFarzand = ModateEntezar + Convert.ToInt32(q1.CodePersoneli);

                                //List3.Add(item);
                            }
                        }
                    }

                    List<AazaSandogh> List4 = new List<AazaSandogh>();
                    FrmRizTakhirVaTajil frm = new FrmRizTakhirVaTajil(this);
                    int tk = 0;
                    int co = 0;

                    if (xtraTabControl2.SelectedTabPageIndex == 0)
                    {

                        List4.AddRange(List01);
                        List4.AddRange(List02);
                        frm.gridControl.DataSource = List4;
                        tk = _Takhir + _Takhir1 + _Takhir2;
                        co = _Count + _Count1 + _Count2;
                        if (tk < 0)
                        {

                            string _SumTakhir = (tk / co).ToString("n0");
                            frm.txtSharhFormul.Text = "میانگین تعداد روزهای تأخیر = " + "جمع کل روزهای تأخیر و تعجیل تقسیم بر تعداد آنها" + " ==> " +
                                _SumTakhir + " = ( " + co.ToString() + " / " + tk.ToString("n0") + " )";

                        }
                        else
                        {
                            string _SumTakhir = "0";
                            frm.txtSharhFormul.Text = "میانگین تعداد روزهای تأخیر " + " ==> " + _SumTakhir;

                        }
                        frm.ShowDialog();
                    }
                    else if (xtraTabControl2.SelectedTabPageIndex == 1)
                    {
                        List4.AddRange(List03);
                        frm.gridControl.DataSource = List4;
                        tk = _Takhir1 + _Takhir2;
                        co = _Count1 + _Count2;

                        if (tk < 0)
                        {
                            string _SumTakhir = (tk / co).ToString("n0");
                            frm.txtSharhFormul.Text = "میانگین تعداد روزهای تأخیر = " + "جمع کل روزهای تأخیر و تعجیل تقسیم بر تعداد آنها" + " ==> " +
                                _SumTakhir + " = ( " + co.ToString() + " / " + tk.ToString("n0") + " )";

                        }
                        else
                        {
                            string _SumTakhir = "0";
                            frm.txtSharhFormul.Text = "میانگین تعداد روزهای تأخیر " + " ==> " + _SumTakhir;

                        }
                        frm.ShowDialog();

                    }
                    else if (xtraTabControl2.SelectedTabPageIndex == 2)
                    {
                        List4.AddRange(List01);
                        List4.AddRange(List02);
                        List4.AddRange(List03);
                        frm.gridControl.DataSource = List4;
                        tk = _Takhir + _Takhir1 + _Takhir2;
                        co = _Count + _Count1 + _Count2;

                        if (tk < 0)
                        {
                            string _SumTakhir = (tk / co).ToString("n0");
                            frm.txtSharhFormul.Text = "میانگین تعداد روزهای تأخیر = " + "جمع کل روزهای تأخیر و تعجیل تقسیم بر تعداد آنها" + " ==> " +
                                _SumTakhir + " = ( " + co.ToString() + " / " + tk.ToString("n0") + " )";

                        }
                        else
                        {
                            string _SumTakhir = "0";
                            frm.txtSharhFormul.Text = "میانگین تعداد روزهای تأخیر " + " ==> " + _SumTakhir;

                        }
                        frm.ShowDialog();

                    }

                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }

        private void xtraTabControl2_SelectedPageChanged(object sender, DevExpress.XtraTab.TabPageChangedEventArgs e)
        {
            List<AazaSandogh> List4 = new List<AazaSandogh>();
            if (xtraTabControl2.SelectedTabPageIndex == 0)
            {
                if (List1.Count > 0)
                    List4.AddRange(List1);
                if (List2.Count > 0)
                    List4.AddRange(List2);
                if (List4.Count > 0)
                    gridControl6.DataSource = List4.OrderByDescending(s => s.TedadeFarzand);
            }
            else if (xtraTabControl2.SelectedTabPageIndex == 1)
            {
                if (List3.Count > 0)
                    List4.AddRange(List3);
                if (List4.Count > 0)
                    gridControl5.DataSource = List4.OrderByDescending(s => s.TedadeFarzand);
            }
            else if (xtraTabControl2.SelectedTabPageIndex == 2)
            {

                if (List1.Count > 0)
                    List4.AddRange(List1);
                if (List2.Count > 0)
                    List4.AddRange(List2);
                if (List3.Count > 0)
                    List4.AddRange(List3);
                if (List4.Count > 0)
                    gridControl4.DataSource = List4.OrderByDescending(s => s.TedadeFarzand);

            }

        }
    }
}