using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace Sandogh_PG.Forms
{
    public partial class FrmNobatbandiVam : DevExpress.XtraEditors.XtraForm
    {
        public FrmNobatbandiVam()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Sandogh_PG.MyContext dbContext = new Sandogh_PG.MyContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.AazaSandoghs.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    aazaSandoghsBindingSource.DataSource = dbContext.AazaSandoghs.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}